server:
  port: 8080
  url: http://127.0.0.1:8080
  session:
    timeout: 3600
spring:
  datasource:
    url:  jdbc:postgresql://localhost:5432/jference-db
    username: postgres
    password: mysecretpassword
    initialization-mode: always
    platform: postgres
  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
#    database: postgresql
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
logging:
  level:
    cz:
      markovd: debug
