server:
  port: 8080
  url: http://127.0.0.1:8080
  session:
    timeout: 3600

spring:
  datasource:
    url:  jdbc:postgresql://localhost:5432e/vyv_jference
    username: postgres
    password: mysecretpassword
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: false
    hibernate:
      ddl-auto: create
    database: postgresql